# Generated by Django 5.1.1 on 2024-09-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nomedaempresa', models.CharField(max_length=50)),
            ],
        ),
    ]
