# Generated by Django 5.1.1 on 2024-09-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbi', '0002_empresa_nomefantasia'),
    ]

    operations = [
        migrations.CreateModel(
            name='area',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nomefantasia', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nomedaempresa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nomefantasia',
            field=models.CharField(max_length=50),
        ),
    ]
