# Generated by Django 5.1.1 on 2024-09-17 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbi', '0003_area_alter_empresa_nomedaempresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='nomefantasia',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
