# Generated by Django 5.1.1 on 2024-09-17 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbi', '0004_alter_empresa_nomefantasia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='nomefantasia',
            new_name='nomearea',
        ),
    ]
