# Generated by Django 5.1.1 on 2024-09-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbi', '0005_rename_nomefantasia_area_nomearea'),
    ]

    operations = [
        migrations.CreateModel(
            name='proposta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numeroproposta', models.CharField(blank=True, max_length=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tagequip', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
