# Generated by Django 5.1.1 on 2024-09-17 21:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbi', '0006_proposta_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='Area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresa_Area', to='rbi.area'),
        ),
    ]
