# Generated by Django 5.1.1 on 2024-09-17 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbi', '0008_remove_empresa_area_area_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='Empresa',
        ),
        migrations.AddField(
            model_name='area',
            name='Area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empresa_area', to='rbi.empresa'),
        ),
    ]
