# Generated by Django 5.1.1 on 2024-09-18 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbi', '0011_remove_empresa_nomedaempresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='Empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='area_empresa', to='rbi.empresa'),
        ),
    ]
