# Generated by Django 5.1.1 on 2024-09-18 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbi', '0012_alter_area_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='Area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='area_tag', to='rbi.area'),
        ),
    ]
