# Generated by Django 5.1.1 on 2024-09-18 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbi', '0013_tag_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposta',
            name='Tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tag_proposta', to='rbi.tag'),
        ),
    ]
