# Generated by Django 5.1.1 on 2024-09-18 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbi', '0014_proposta_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='razaosocial',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
