# Generated by Django 5.1.1 on 2024-09-18 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbi', '0016_tag_empresa1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='Area',
            field=models.ForeignKey(blank=True, limit_choices_to=models.Q(('pk__gt', 0)), null=True, on_delete=django.db.models.deletion.PROTECT, related_name='area_tag', to='rbi.area'),
        ),
    ]
