# Generated by Django 5.1.1 on 2024-09-18 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbi', '0017_alter_tag_area'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='Empresa1',
        ),
        migrations.AlterField(
            model_name='tag',
            name='Area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='area_tag', to='rbi.area'),
        ),
    ]
