# Generated by Django 5.1.1 on 2024-09-23 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbi', '0020_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
