# Generated by Django 5.1.1 on 2024-09-23 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbi', '0021_delete_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='dados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dataavaliacao', models.DateField()),
                ('metodoavalia', models.CharField(blank=True, max_length=20, null=True)),
                ('periodoavalia', models.IntegerField(blank=True, max_length=2, null=True)),
                ('Dados', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dadospro_proposta', to='rbi.proposta')),
            ],
        ),
    ]
