# Generated by Django 5.1.1 on 2024-09-23 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbi', '0022_dados'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dados',
        ),
    ]
