# Generated by Django 5.1.1 on 2024-09-23 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbi', '0023_delete_dados'),
    ]

    operations = [
        migrations.CreateModel(
            name='dados',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Dados', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dados_numeroproposta', to='rbi.proposta')),
            ],
        ),
    ]
