# Generated by Django 5.1.1 on 2024-09-23 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbi', '0024_dados'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados',
            name='dataavaliacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dados',
            name='metodoavalia',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dados',
            name='periodoavalia',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
