# Generated by Django 5.1.1 on 2024-09-24 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbi', '0025_dados_dataavaliacao_dados_metodoavalia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='componente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='proposta',
            name='Area2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='area2_tag', to='rbi.area'),
        ),
        migrations.AddField(
            model_name='proposta',
            name='Empresa2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='area_empresa2', to='rbi.empresa'),
        ),
        migrations.AddField(
            model_name='tag',
            name='componente',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
