# Generated by Django 5.1.1 on 2024-09-24 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbi', '0026_componente_proposta_area2_proposta_empresa2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposta',
            name='Area2',
        ),
        migrations.RemoveField(
            model_name='proposta',
            name='Empresa2',
        ),
    ]
