# Generated by Django 5.1.1 on 2024-09-25 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbi', '0027_remove_proposta_area2_remove_proposta_empresa2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='componente',
        ),
        migrations.AddField(
            model_name='componente',
            name='Area2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='area_empresa2', to='rbi.area'),
        ),
        migrations.AddField(
            model_name='componente',
            name='Empresa2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='area_empresa1', to='rbi.empresa'),
        ),
        migrations.AddField(
            model_name='componente',
            name='componente',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='componente',
            name='tagequip2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='area_tagequip', to='rbi.tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='Empresa1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='area_empresa2', to='rbi.empresa'),
        ),
    ]
