# Generated by Django 4.2.16 on 2024-10-11 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbi', '0028_remove_tag_componente_componente_area2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='equipamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dataavaliacao', models.DateField(blank=True, null=True)),
                ('metodoavalia', models.CharField(blank=True, max_length=20, null=True)),
                ('periodoavalia', models.IntegerField(blank=True, null=True)),
                ('Dados', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dados_numeroproposta', to='rbi.proposta')),
            ],
        ),
        migrations.AlterField(
            model_name='area',
            name='Empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='areas', to='rbi.empresa'),
        ),
        migrations.DeleteModel(
            name='dados',
        ),
    ]
