# Generated by Django 4.2.16 on 2024-10-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbi', '0029_equipamento_alter_area_empresa_delete_dados'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
