# Generated by Django 4.2.16 on 2024-10-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbi', '0030_empresa_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
