# Generated by Django 4.2.16 on 2024-10-11 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbi', '0031_area_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area',
            old_name='Empresa',
            new_name='empresa',
        ),
        migrations.RenameField(
            model_name='area',
            old_name='nomearea',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='nomefantasia',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='razaosocial',
        ),
    ]
