# Generated by Django 4.2.16 on 2024-10-12 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbi', '0038_rename_area_tag_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='area',
            new_name='Area',
        ),
    ]
