# Generated by Django 4.2.16 on 2024-10-12 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbi', '0039_rename_area_tag_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='Area',
            new_name='area',
        ),
    ]
