# Generated by Django 4.2.16 on 2024-10-12 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbi', '0043_proposta_componente1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposta',
            name='Area3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area_empresa4', to='rbi.area'),
        ),
        migrations.AlterField(
            model_name='proposta',
            name='Empresa3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area_empresa3', to='rbi.empresa'),
        ),
    ]
