# Generated by Django 4.2.16 on 2024-10-12 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbi', '0044_alter_proposta_area3_alter_proposta_empresa3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposta',
            old_name='Tag',
            new_name='Tag1',
        ),
    ]
