# Generated by Django 4.2.16 on 2024-10-12 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbi', '0045_rename_tag_proposta_tag1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposta',
            old_name='Tag1',
            new_name='tagequip3',
        ),
    ]
