# Generated by Django 4.2.16 on 2024-10-13 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbi', '0048_alter_area_id_alter_empresa_id_alter_tag_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipamento',
            old_name='Dados',
            new_name='numeroproposta',
        ),
    ]
