# Generated by Django 4.2.16 on 2024-10-13 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbi', '0050_rename_empresa1_tag_empresa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tagequip',
            new_name='tag',
        ),
    ]
