# Generated by Django 4.2.16 on 2024-10-13 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbi', '0052_rename_empresa2_componente_empresa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='componente',
            old_name='Area2',
            new_name='Area',
        ),
        migrations.RemoveField(
            model_name='componente',
            name='tagequip2',
        ),
        migrations.AddField(
            model_name='componente',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='area_tag1', to='rbi.tag'),
        ),
    ]
