# Generated by Django 4.2.16 on 2024-10-13 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbi', '0053_rename_area2_componente_area_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposta',
            old_name='Area3',
            new_name='Area',
        ),
        migrations.RenameField(
            model_name='proposta',
            old_name='Empresa3',
            new_name='Empresa',
        ),
        migrations.RenameField(
            model_name='proposta',
            old_name='componente1',
            new_name='componente',
        ),
        migrations.RenameField(
            model_name='proposta',
            old_name='tagequip3',
            new_name='tag',
        ),
    ]
