# Generated by Django 4.2.16 on 2024-10-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbi', '0054_rename_area3_proposta_area_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipamento',
            old_name='metodoavalia',
            new_name='descricaoprocesso',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='dataavaliacao',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='periodoavalia',
        ),
        migrations.AddField(
            model_name='equipamento',
            name='nomequipamento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='tipoequipamento',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
