# Generated by Django 4.2.16 on 2024-10-14 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbi', '0057_remove_tag_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componente',
            name='Area',
        ),
        migrations.RemoveField(
            model_name='componente',
            name='Empresa',
        ),
    ]
