# Generated by Django 4.2.16 on 2024-10-15 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbi', '0059_remove_proposta_area_remove_proposta_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='numeroproposta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_componente1', to='rbi.proposta'),
        ),
        migrations.CreateModel(
            name='Abacomponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipocomponenteapi', models.CharField(blank=True, max_length=20, null=True)),
                ('eficienciajunta', models.CharField(blank=True, max_length=20, null=True)),
                ('diametrocomponente', models.CharField(blank=True, max_length=20, null=True)),
                ('raiodacurva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('razaocentraltorisferico', models.DecimalField(decimal_places=2, max_digits=10)),
                ('raiocentraltorisferico', models.DecimalField(decimal_places=2, max_digits=10)),
                ('raiomenortorisferico', models.DecimalField(decimal_places=2, max_digits=10)),
                ('angulocone', models.DecimalField(decimal_places=2, max_digits=10)),
                ('componentesoldado', models.BooleanField()),
                ('numeroproposta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_componente2', to='rbi.proposta')),
            ],
        ),
    ]
