# Generated by Django 4.2.16 on 2024-10-15 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbi', '0060_alter_equipamento_numeroproposta_abacomponente'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='equipamento',
            new_name='Abaequipamento',
        ),
        migrations.CreateModel(
            name='Abacondicoesoperacionais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pressãoprojeto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('temperaturaprojeto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('temperaturamaxima', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tracoaquecimento', models.BooleanField()),
                ('vazamentovapor', models.BooleanField()),
                ('monitoramento', models.CharField(blank=True, max_length=20, null=True)),
                ('injecao', models.CharField(blank=True, max_length=20, null=True)),
                ('deadleg', models.CharField(blank=True, max_length=20, null=True)),
                ('tipoinspecaodeadleg', models.CharField(blank=True, max_length=20, null=True)),
                ('numeroproposta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_componente3', to='rbi.proposta')),
            ],
        ),
    ]
