# Generated by Django 4.2.16 on 2024-10-15 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbi', '0061_rename_equipamento_abaequipamento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abacomponente',
            old_name='razaocentraltorisferico',
            new_name='razaomaiormenoreixos',
        ),
    ]
