# Generated by Django 4.2.16 on 2024-10-15 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbi', '0063_abadadosgerais'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abadadosgerais',
            old_name='FMS',
            new_name='fms',
        ),
        migrations.CreateModel(
            name='Abavolumemassa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volumeequip', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volumecomponente', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numeroproposta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag_componente5', to='rbi.proposta')),
            ],
        ),
    ]
