# Generated by Django 4.2.16 on 2024-10-16 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbi', '0064_rename_fms_abadadosgerais_fms_abavolumemassa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='area_tag', to='rbi.area'),
        ),
    ]
